services:
  - type: web
    name: health-system
    env: python
    plan: free 
    buildCommand: poetry install
    startCommand: poetry run gunicorn health_system.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: health_system.settings
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: db.sqlite3
          property: connectionString
databases:
  - name: your-db-name
    plan: free
