services:
  - type: web
    name: health-system
    env: python
    plan: free 
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn health_system.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: health_system.settings
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        value: sqlite:///db.sqlite3
