# Generated by Django 5.2 on 2025-04-26 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='enrolled_programs',
            field=models.ManyToManyField(to='core.healthprogram'),
        ),
    ]
